### ISSUE TITLE
Error: Found incompatible module

### ISSUE THREAD

**Issue by ghost** [hebertcisco/nest-sns#175]
Looks like I'm unable to install this npm module. I'm getting the following error:

```
error nest-sns@0.1.5: The platform "darwin" is incompatible with this module.
error Found incompatible module.
```
This might be due to the OS property set to exclude darwin builds. Please advise.

**Comment by hebertcisco** [comment]
I left it unsupported on Darwin systems (MacOs) as I didn't have time to test it on a mac system.

![image](https://user-images.githubusercontent.com/45374044/229177932-67317f19-7caf-49c0-8bab-c86d417becd7.png)

How about you make a contribution and adjust this package.json by removing the `"!darwin"`, leaving `"darwin"` and if your system is arm, change `"!arm"`, by `"arm"`,

**Comment by hebertcisco** [comment]
@denisatfn  https://github.com/hebertcisco/nest-sns/releases/tag/v0.1.6

**Comment by art1c0** [comment]
The module is still not supported on M1 mac (arm64):
`Unsupported platform for nest-sns@0.1.6: wanted {"os":"darwin,linux,win32","arch":"x64,arm,!mips"} (current: {"os":"darwin","arch":"arm64"})`
Please add this architecture as well.

**Comment by hebertcisco** [comment]
@art1c0 Do you have any arm64 devices, a mac that could test the module and let you know if this error still persists?

https://github.com/hebertcisco/nest-sns/pull/240
